### ISSUE TITLE
WPF Command CanExecute Sample

### ISSUE THREAD

**Issue by shaggygi** [CommunityToolkit/MVVM-Samples#68]
Anyone have examples how to use ICommand and CanExecute using WPF?  I thought I came across some mentions you must add more in addition to what is provided with the MVVM toolkit.

Any help is appreciated.

**Comment by andermikael** [comment]
A sample program showing how I use binding to command in **WPF**.

[MeCommand](https://github.com/andermikael/MeCommand)

I'm using *Community Toolkit MVVM* and *RelayCommand* and *AsyncRelayCommand*. Instead of ICommand I'm using *IRelayCommand* and *IAsyncRelayCommand*

This is the first attempt to use *Community Toolkit MVVM*  so there might be errors or strangeness. The program works!

Hope this helps!
// Anders

**Comment by shaggygi** [comment]
Thanks for the tidbits @andermikael 👍
